# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 50bc1ff4de41332e4a4f2d4de154bf5c1bbc054be8440f14c5d09051bab34650085fb8c1dfd7d575d0dd5653bfbec633400b581d652287a30b176c2c3a51f7ff

test:
  secret_key_base: 399899f47f28503c9fd74d786a890611db007192defefd746c56f9a0ed0a99e351639dda4f4e5b23a3a96b86d5817313fde92badbb6141b2378edca1050b7d92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
